/** Stable action codes written to audit_logs (append-only). */
export enum AuditAction {
  PAYMENT_MARK_PAID = 'PAYMENT_MARK_PAID',
  PAYMENT_REFUND = 'PAYMENT_REFUND',

  INVENTORY_MANUAL_MOVEMENT = 'INVENTORY_MANUAL_MOVEMENT',
  INVENTORY_TRANSFER = 'INVENTORY_TRANSFER',
  RESERVATION_RELEASE = 'RESERVATION_RELEASE',

  AUTH_LOGOUT_ALL = 'AUTH_LOGOUT_ALL',
  AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD',
  AUTH_REVOKE_SESSION = 'AUTH_REVOKE_SESSION',
  AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD',

  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  WAREHOUSE_CREATE = 'WAREHOUSE_CREATE',
  WAREHOUSE_UPDATE = 'WAREHOUSE_UPDATE',
  WAREHOUSE_DELETE = 'WAREHOUSE_DELETE',

  ORDER_CREATE_MANUAL = 'ORDER_CREATE_MANUAL',
}
